default_language_version:
    python: python3.8

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3298ddab3c13dd77d6ce1fc0baf97691430d84b0  # frozen: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: fix-encoding-pragma
    args: ['--remove']
  - id: forbid-new-submodules
  - id: mixed-line-ending
    args: ['--fix=lf']
    description: Forces to replace line ending by the UNIX 'lf' character.
  - id: pretty-format-json
    args: ['--no-sort-keys']
  - id: check-added-large-files
    args: ['--maxkb=500']
  - id: no-commit-to-branch
    args: [--branch, staging]

- repo: local
  hooks:
  - id: isort
    name: isort
    entry: isort --atomic .
    language: system
    always_run: true

  - id: linter
    name: pylint
    exclude: local/
    entry: pytest --flake8 -m flake8 --cache-clear --ignore=E501 transform
    language: system
    always_run: true
