SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CORE].[HUB_PERSON](
	[H_PERSON_KEY] [varchar](100) NOT NULL,
	[PERSON_NO] [varchar](100) NOT NULL,
	[LOAD_DATE] [timestamp] NOT NULL,
	[RECORD_SOURCE] [varchar](100) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [CORE].[HUB_PERSON] ADD  CONSTRAINT [HUB_CUSTOMER_PK] PRIMARY KEY CLUSTERED
(
	[H_PERSON_KEY] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [CORE].[HUB_PERSON] ADD  CONSTRAINT [HUB_CUSTOMER_UN] UNIQUE NONCLUSTERED
(
	[PERSON_NO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
