SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CORE].[LNK_CLICK](
	[L_CLICK_KEY] [varchar](100) NOT NULL,
	[H_PERSON_KEY] [varchar](100) NOT NULL,
	[H_TOUCHPOINT_KEY] [varchar](100) NOT NULL,
	[LOAD_DATE] [timestamp] NOT NULL,
	[RECORD_SOURCE] [varchar](100) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [CORE].[LNK_CLICK] ADD  CONSTRAINT [LNK_CLICK_PK] PRIMARY KEY CLUSTERED
(
	[L_CLICK_KEY] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [CORE].[LNK_CLICK]  WITH CHECK ADD  CONSTRAINT [LNK_CLICK_FK_CUSTOMER] FOREIGN KEY([H_PERSON_KEY])
REFERENCES [CORE].[HUB_PERSON] ([H_PERSON_KEY])
GO
ALTER TABLE [CORE].[LNK_CLICK] CHECK CONSTRAINT [LNK_CLICK_FK_CUSTOMER]
GO
ALTER TABLE [CORE].[LNK_CLICK]  WITH CHECK ADD  CONSTRAINT [LNK_CLICK_FK_TOUCHPOINT] FOREIGN KEY([H_TOUCHPOINT_KEY])
REFERENCES [CORE].[HUB_TOUCHPOINT] ([H_TOUCHPOINT_KEY])
GO
ALTER TABLE [CORE].[LNK_CLICK] CHECK CONSTRAINT [LNK_CLICK_FK_TOUCHPOINT]
GO
