SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CORE].[SAT_PERSON_IDENTIFIER](
	[H_PERSON_KEY] [varchar](100) NOT NULL,
	[LOAD_DATE] [timestamp] NOT NULL,
	[TYPE] [varchar](100) NOT NULL,
	[VALUE] [varchar](100) NOT NULL,
	[RECORD_SOURCE] [varchar](100) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [CORE].[SAT_PERSON_IDENTIFIER] ADD  CONSTRAINT [SAT_CUSTOMER_IDENTIFIER_PK] PRIMARY KEY CLUSTERED
(
	[H_PERSON_KEY] ASC,
	[LOAD_DATE] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [CORE].[SAT_PERSON_IDENTIFIER]  WITH CHECK ADD  CONSTRAINT [SAT_CUSTOMER_IDENTIFIER_FK] FOREIGN KEY([H_PERSON_KEY])
REFERENCES [CORE].[HUB_PERSON] ([H_PERSON_KEY])
GO
ALTER TABLE [CORE].[SAT_PERSON_IDENTIFIER] CHECK CONSTRAINT [SAT_CUSTOMER_IDENTIFIER_FK]
GO
