name: Build and Deploy Transform Azure Function

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: qurixtechnology/base-workflows/.github/workflows/build_python_azure_function.yml@main
    with:
      python_version: 3.8
      build_path: .
      artifact_name: "python-app-transform-${{ github.sha }}"
      current_branch: ${{ github.head_ref }}


  deploy:
    uses: qurixtechnology/base-workflows/.github/workflows/deploy_python_azure_function.yml@main
    needs: build
    with:
      azure_function_resource_group: rg-dev-sunrise-core
      azure_function_app_name: func-dev-compute-transform-sunrise-core
      azure_function_app_build_path: .
      environment: dev
      artifact_name: "python-app-transform-${{ github.sha }}"
    secrets: inherit
    if: github.event.pull_request.merged == 'true'

